"use client";
import React from "react";
import _styles from "./css/classes.module.css";
import * as _utils from "./utils";
import Block from "./_Builtin/Block";
import Grid from "./_Builtin/Grid";
import HtmlEmbed from "./_Builtin/HtmlEmbed";
import Image from "./_Builtin/Image";
import Link from "./_Builtin/Link";
import Paragraph from "./_Builtin/Paragraph";

export function Footer({ as: _Component = Block, variant = "Base" }) {
  const _styleVariantMap = {
    Base: "",
    Variant: "w-variant-919f5722-282d-5fed-ad48-f950ccbe501d",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <_Component
      className={_utils.cx(_styles, "footer_component", _activeStyleVariant)}
      id={_utils.cx(
        _styles,
        "w-node-a31bb196-bc4d-f0f9-3024-5ebe523a6ee1-523a6ee1"
      )}
      tag="footer"
    >
      <Block
        className={_utils.cx(_styles, "footer_divider", _activeStyleVariant)}
        id={_utils.cx(
          _styles,
          "w-node-_89953f3e-aedf-fd6c-83af-8f87cba6f134-523a6ee1"
        )}
        tag="div"
      />
      <Block
        className={_utils.cx(
          _styles,
          "footer_top-wrapper",
          _activeStyleVariant
        )}
        tag="div"
      >
        <Block
          className={_utils.cx(_styles, "container-large", _activeStyleVariant)}
          tag="div"
        >
          <Grid
            className={_utils.cx(_styles, "footer_top", _activeStyleVariant)}
            tag="div"
          >
            <Block
              className={_utils.cx(
                _styles,
                "footer_menu-column",
                _activeStyleVariant
              )}
              id={_utils.cx(
                _styles,
                "w-node-a31bb196-bc4d-f0f9-3024-5ebe523a6ee4-523a6ee1"
              )}
              tag="div"
            >
              <Paragraph
                className={_utils.cx(
                  _styles,
                  "footer_menu-title",
                  _activeStyleVariant
                )}
              >
                {"Каталог"}
              </Paragraph>
              <Block
                className={_utils.cx(
                  _styles,
                  "footer_link-list",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Офисные кресла"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Игровые кресла"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Аксессуары"}
                </Link>
              </Block>
            </Block>
            <Block
              className={_utils.cx(
                _styles,
                "footer_menu-column",
                _activeStyleVariant
              )}
              id={_utils.cx(
                _styles,
                "w-node-a31bb196-bc4d-f0f9-3024-5ebe523a6eed-523a6ee1"
              )}
              tag="div"
            >
              <Paragraph
                className={_utils.cx(
                  _styles,
                  "footer_menu-title",
                  _activeStyleVariant
                )}
              >
                {"Бренды"}
              </Paragraph>
              <Block
                className={_utils.cx(
                  _styles,
                  "footer_link-list",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "/brands/office-herman-miller",
                  }}
                >
                  {"Herman Miller"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "/brands/office-haworth",
                  }}
                >
                  {"Haworth"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "/brands/office-libernovo",
                  }}
                >
                  {"Steelcase"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "/brands/office-libernovo",
                  }}
                >
                  {"LiberNovo"}
                </Link>
              </Block>
            </Block>
            <Block
              className={_utils.cx(
                _styles,
                "footer_menu-column",
                _activeStyleVariant
              )}
              id={_utils.cx(
                _styles,
                "w-node-_5af76e7b-f03a-1f06-1efd-6ad8f8ca7d41-523a6ee1"
              )}
              tag="div"
            >
              <Paragraph
                className={_utils.cx(
                  _styles,
                  "footer_menu-title",
                  _activeStyleVariant
                )}
              >
                {"Покупателям"}
              </Paragraph>
              <Block
                className={_utils.cx(
                  _styles,
                  "footer_link-list",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Корпоративным клиентам"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Сервисный центр Herman Miller"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Гарантия и сервис"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Оплата и доставка"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Возврат"}
                </Link>
              </Block>
            </Block>
            <Block
              className={_utils.cx(
                _styles,
                "footer_menu-column",
                _activeStyleVariant
              )}
              id={_utils.cx(
                _styles,
                "w-node-a31bb196-bc4d-f0f9-3024-5ebe523a6ef8-523a6ee1"
              )}
              tag="div"
            >
              <Paragraph
                className={_utils.cx(
                  _styles,
                  "footer_menu-title",
                  _activeStyleVariant
                )}
              >
                {"О компании"}
              </Paragraph>
              <Block
                className={_utils.cx(
                  _styles,
                  "footer_link-list",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Реквизиты"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Блог"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Контакты"}
                </Link>
              </Block>
            </Block>
            <Block
              className={_utils.cx(
                _styles,
                "footer_menu-column",
                _activeStyleVariant
              )}
              id={_utils.cx(
                _styles,
                "w-node-e8d27cbf-78cb-9d75-ef73-1026e9019a1b-523a6ee1"
              )}
              tag="div"
            >
              <Paragraph
                className={_utils.cx(
                  _styles,
                  "footer_menu-title",
                  _activeStyleVariant
                )}
              >
                {"Контакты"}
              </Paragraph>
              <Block
                className={_utils.cx(
                  _styles,
                  "footer_link-list",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "tel:+74951202219",
                  }}
                >
                  {"+7 495 120-22-19"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "mailto:@info@millsey.ru",
                  }}
                >
                  {"info@millsey.ru"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "https://wa.me/79032555502",
                    target: "_blank",
                  }}
                >
                  {"WhatsApp"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "https://t.me/millsey_msk",
                    target: "_blank",
                  }}
                >
                  {"Telegram"}
                </Link>
              </Block>
            </Block>
          </Grid>
        </Block>
      </Block>
      <Block
        className={_utils.cx(_styles, "footer_divider", _activeStyleVariant)}
        id={_utils.cx(
          _styles,
          "w-node-fdf09ca8-1a36-b6e5-0f00-7cf55c1a579b-523a6ee1"
        )}
        tag="div"
      />
      <Block
        className={_utils.cx(
          _styles,
          "footer_brand-wrapper",
          _activeStyleVariant
        )}
        tag="div"
      >
        <Block
          className={_utils.cx(_styles, "container-full", _activeStyleVariant)}
          tag="div"
        >
          <Block
            className={_utils.cx(_styles, "footer_brand", _activeStyleVariant)}
            tag="div"
          >
            <Block
              className={_utils.cx(
                _styles,
                "footer_brand-marquee",
                _activeStyleVariant
              )}
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "footer_brand-track",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Block
                  className={_utils.cx(
                    _styles,
                    "footer_brand-group",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <Image
                    alt=""
                    className={_utils.cx(
                      _styles,
                      "footer_brand-logo",
                      _activeStyleVariant
                    )}
                    height="auto"
                    loading="lazy"
                    src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/6904f9516140f2317e33a578_Millsey.svg"
                    width="auto"
                  />
                  <Block
                    className={_utils.cx(
                      _styles,
                      "footer_brand-media",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdcf32c16471dd7364be4_w-hm2521928sayl07-1.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69be9e2f28ff6498999b49f7_herman-miller-aeron-banner-millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69b93bb9fbcc32b36dd8d14c_LiberNovo.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdbf9a502355ad592e5cf_w-hm2546179vantum08.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/693d870628b81437d76b253c_corporate_millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69bea0b658dbc8e88f85a7de_herman-miller-gaming-chair-millsey.webp"
                      width="auto"
                    />
                  </Block>
                  <Image
                    alt=""
                    className={_utils.cx(
                      _styles,
                      "footer_brand-logo",
                      _activeStyleVariant
                    )}
                    height="auto"
                    loading="lazy"
                    src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/6904f9516140f2317e33a578_Millsey.svg"
                    width="auto"
                  />
                  <Block
                    className={_utils.cx(
                      _styles,
                      "footer_brand-media",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdcf32c16471dd7364be4_w-hm2521928sayl07-1.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69be9e2f28ff6498999b49f7_herman-miller-aeron-banner-millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69b93bb9fbcc32b36dd8d14c_LiberNovo.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdbf9a502355ad592e5cf_w-hm2546179vantum08.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/693d870628b81437d76b253c_corporate_millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69bea0b658dbc8e88f85a7de_herman-miller-gaming-chair-millsey.webp"
                      width="auto"
                    />
                  </Block>
                </Block>
                <Block
                  className={_utils.cx(
                    _styles,
                    "footer_brand-group",
                    _activeStyleVariant
                  )}
                  tag="div"
                >
                  <Image
                    alt=""
                    className={_utils.cx(
                      _styles,
                      "footer_brand-logo",
                      _activeStyleVariant
                    )}
                    height="auto"
                    loading="lazy"
                    src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/6904f9516140f2317e33a578_Millsey.svg"
                    width="auto"
                  />
                  <Block
                    className={_utils.cx(
                      _styles,
                      "footer_brand-media",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdcf32c16471dd7364be4_w-hm2521928sayl07-1.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69be9e2f28ff6498999b49f7_herman-miller-aeron-banner-millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69b93bb9fbcc32b36dd8d14c_LiberNovo.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdbf9a502355ad592e5cf_w-hm2546179vantum08.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/693d870628b81437d76b253c_corporate_millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69bea0b658dbc8e88f85a7de_herman-miller-gaming-chair-millsey.webp"
                      width="auto"
                    />
                  </Block>
                  <Image
                    alt=""
                    className={_utils.cx(
                      _styles,
                      "footer_brand-logo",
                      _activeStyleVariant
                    )}
                    height="auto"
                    loading="lazy"
                    src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/6904f9516140f2317e33a578_Millsey.svg"
                    width="auto"
                  />
                  <Block
                    className={_utils.cx(
                      _styles,
                      "footer_brand-media",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdcf32c16471dd7364be4_w-hm2521928sayl07-1.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69be9e2f28ff6498999b49f7_herman-miller-aeron-banner-millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69b93bb9fbcc32b36dd8d14c_LiberNovo.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/68cbdbf9a502355ad592e5cf_w-hm2546179vantum08.webp"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/693d870628b81437d76b253c_corporate_millsey.avif"
                      width="auto"
                    />
                    <Image
                      alt=""
                      className={_utils.cx(
                        _styles,
                        "footer_brand-image",
                        _activeStyleVariant
                      )}
                      height="auto"
                      loading="lazy"
                      src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/69bea0b658dbc8e88f85a7de_herman-miller-gaming-chair-millsey.webp"
                      width="auto"
                    />
                  </Block>
                </Block>
              </Block>
            </Block>
            <Image
              alt=""
              className={_utils.cx(
                _styles,
                "footer_brand-logo",
                "is-mobile",
                _activeStyleVariant
              )}
              height="auto"
              loading="lazy"
              src="https://cdn.prod.website-files.com/6893878d254e1daa66e3f933/6904f9516140f2317e33a578_Millsey.svg"
              width="auto"
            />
          </Block>
        </Block>
      </Block>
      <Block
        className={_utils.cx(_styles, "footer_divider", _activeStyleVariant)}
        id={_utils.cx(
          _styles,
          "w-node-a8e06d82-b716-ad69-9646-9c5a8a15feb2-523a6ee1"
        )}
        tag="div"
      />
      <Block
        className={_utils.cx(
          _styles,
          "footer_bottom-wrapper",
          _activeStyleVariant
        )}
        tag="div"
      >
        <Block
          className={_utils.cx(_styles, "container-large", _activeStyleVariant)}
          tag="div"
        >
          <Block
            className={_utils.cx(_styles, "footer_bottom", _activeStyleVariant)}
            id={_utils.cx(
              _styles,
              "w-node-e0b6bb66-3742-6485-17c6-7074f378303f-523a6ee1"
            )}
            tag="div"
          >
            <Block
              className={_utils.cx(
                _styles,
                "footer_bottom-cell",
                _activeStyleVariant
              )}
              tag="div"
            >
              <Paragraph
                className={_utils.cx(
                  _styles,
                  "footer_bottom-text",
                  _activeStyleVariant
                )}
              >
                {"MILLSEY — официальный интернет-бутик офисной мебели"}
              </Paragraph>
            </Block>
            <Block
              className={_utils.cx(
                _styles,
                "footer_bottom-cell",
                _activeStyleVariant
              )}
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "footer_legal-list",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_legal-link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Оферта"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_legal-link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Условия"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_legal-link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Конфиденциальность"}
                </Link>
                <Link
                  block=""
                  button={false}
                  className={_utils.cx(
                    _styles,
                    "footer_legal-link",
                    "link-underline",
                    _activeStyleVariant
                  )}
                  options={{
                    href: "#",
                  }}
                >
                  {"Персональные данные"}
                </Link>
              </Block>
              <Paragraph
                className={_utils.cx(
                  _styles,
                  "footer_bottom-text",
                  _activeStyleVariant
                )}
              >
                {"© 2026"}
              </Paragraph>
            </Block>
          </Block>
        </Block>
      </Block>
      <HtmlEmbed
        className={_utils.cx(_styles, "u-embed-css", _activeStyleVariant)}
        content=""
        value="%3Cstyle%3E%0A%20%20%40media%20screen%20and%20(min-width%3A%20992px)%20%7B%0A%20%20%20%20.footer_brand-wrapper%3Ahover%20.footer_brand-track%20%7B%0A%20%20%20%20%20%20animation-play-state%3A%20paused%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20%40keyframes%20footerBrandMarquee%20%7B%0A%20%20%20%20from%20%7B%0A%20%20%20%20%20%20transform%3A%20translateX(0)%3B%0A%20%20%20%20%7D%0A%20%20%20%20to%20%7B%0A%20%20%20%20%20%20transform%3A%20translateX(-50%25)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%3C%2Fstyle%3E"
      />
      <HtmlEmbed
        className={_utils.cx(_styles, "u-embed-js", _activeStyleVariant)}
        content=""
        value="%3Cscript%3E%0A%20%20document.addEventListener('DOMContentLoaded'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20isMobile%20%3D%20window.matchMedia('(max-width%3A%20479px)').matches%3B%0A%0A%20%20%20%20if%20(isMobile)%20return%3B%0A%0A%20%20%20%20const%20mediaBlocks%20%3D%20document.querySelectorAll('.footer_brand-media')%3B%0A%0A%20%20%20%20mediaBlocks.forEach((mediaBlock%2C%20blockIndex)%20%3D%3E%20%7B%0A%20%20%20%20%20%20const%20images%20%3D%20mediaBlock.querySelectorAll('.footer_brand-image')%3B%0A%20%20%20%20%20%20if%20(images.length%20%3C%202)%20return%3B%0A%0A%20%20%20%20%20%20let%20current%20%3D%200%3B%0A%0A%20%20%20%20%20%20gsap.set(images%2C%20%7B%0A%20%20%20%20%20%20%20%20yPercent%3A%20100%2C%0A%20%20%20%20%20%20%20%20zIndex%3A%201%2C%0A%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20gsap.set(images%5B0%5D%2C%20%7B%0A%20%20%20%20%20%20%20%20yPercent%3A%200%2C%0A%20%20%20%20%20%20%20%20zIndex%3A%202%2C%0A%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20function%20switchImage()%20%7B%0A%20%20%20%20%20%20%20%20const%20next%20%3D%20(current%20%2B%201)%20%25%20images.length%3B%0A%0A%20%20%20%20%20%20%20%20gsap.set(images%5Bnext%5D%2C%20%7B%0A%20%20%20%20%20%20%20%20%20%20yPercent%3A%20100%2C%0A%20%20%20%20%20%20%20%20%20%20zIndex%3A%203%2C%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20gsap.set(images%5Bcurrent%5D%2C%20%7B%0A%20%20%20%20%20%20%20%20%20%20zIndex%3A%202%2C%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20const%20tl%20%3D%20gsap.timeline()%3B%0A%0A%20%20%20%20%20%20%20%20tl.to(%0A%20%20%20%20%20%20%20%20%20%20images%5Bcurrent%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20yPercent%3A%20-100%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20duration%3A%201.1%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20ease%3A%20'power2.inOut'%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%200%2C%0A%20%20%20%20%20%20%20%20)%3B%0A%0A%20%20%20%20%20%20%20%20tl.to(%0A%20%20%20%20%20%20%20%20%20%20images%5Bnext%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20yPercent%3A%200%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20duration%3A%201.1%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20ease%3A%20'power2.inOut'%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%200%2C%0A%20%20%20%20%20%20%20%20)%3B%0A%0A%20%20%20%20%20%20%20%20tl.set(images%5Bcurrent%5D%2C%20%7B%0A%20%20%20%20%20%20%20%20%20%20yPercent%3A%20100%2C%0A%20%20%20%20%20%20%20%20%20%20zIndex%3A%201%2C%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20tl.set(images%5Bnext%5D%2C%20%7B%0A%20%20%20%20%20%20%20%20%20%20zIndex%3A%202%2C%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20current%20%3D%20next%3B%0A%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20setInterval(switchImage%2C%203200)%3B%0A%20%20%20%20%20%20%7D%2C%20blockIndex%20*%20700)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0A%3C%2Fscript%3E"
      />
    </_Component>
  );
}
